# Generated by Django 5.1.4 on 2026-01-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_operator_page', 'Can view operator page'), ('view_manager_page', 'Can view manager page')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
