# Generated by Django 5.1.4 on 2026-01-05 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_permission', '0001_initial'),
        ('user', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
